### PR TITLE
Dockerized base application

### PR DESCRIPTION
**Pull request by 1ethanhansen**
Fixes # NO OPEN ISSUE

Summary of changes made in this PR:
* Added Dockerfile to specify docker containers
* https://hub.docker.com/r/1ethanhansen/container_analysis_project
* seeing as we can now perform container analysis in a container in a container in a VM, here's a 

Summary of changes to each file:
* Dockerfile : added Dockerfile that specifies python 3.7, all of the needed code, requirements, and the command to run

Signed-off-by: Ethan Hansen <1ethanhansen@gmail.com>

### CODE REVIEW

**Comment by mtarsel** [comment]
I like this idea a lot but perhaps the PR should contain some more documentation about how to use this

**Comment by 1ethanhansen** [comment]
> I like this idea a lot but perhaps the PR should contain some more documentation about how to use this

@mtarsel will do

**Comment by mtarsel** [comment]
as per your last commit in this pr, yes please rebase and squash. LGTM

**Comment by 1ethanhansen** [comment]
@mtarsel freshly squashed!

**Pull request merged**
